name: App CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.1
    - uses: actions/setup-node@v4.0.2
      with:
        node-version: 20.x

    - name: Install dependencies
      run: yarn install

    - name: Run tests
      run: yarn run test

    - uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
